### ISSUE TITLE
Does not build with SBCL

### ISSUE THREAD

**Issue by quicklisp** [adlai/scalpl#1]
14:40 <stassats`> it has (setf name (intern name :keyword)) *exchanges*), where 
	      name is a with-slots slots
    14:40 <stassats`> so, the first time it's can be a string, then it becomes a 
	      keyword, but that's in initial-instance, shouldn't happen twice
    14:43 <stassats`> this line 
    https://github.com/adlai/scalpl/blob/bdccfd817e01d6b938db1301fe465645d225fba3/kraken.lisp#L154

http://report.quicklisp.org/2015-01-09/failure-report/scalpl.html#scalpl has a log.

**Comment by adlai** [comment]
Fixed in 9fa4f91
