### ISSUE TITLE
Does not build - argument count error

### ISSUE THREAD

**Issue by quicklisp** [adlai/scalpl#5]
Build log is here: http://report.quicklisp.org/2016-08-15/failure-report/scalpl.html#scalpl

I get: 

    ; file: /home/quicklisp/quicklisp-controller/dist/build-cache/scalpl/dcddb500ae183a0df38ce2ad4c1cd271502d2738/scalpl-20160815-git/btce.lisp
    ; in: DEFMETHOD GATE-POST ((EQL *BTCE*) T T T) => DEFPARAMETER +KLUDGE+
    ;     (ERROR)
    ; 
    ; caught WARNING:
    ;   The function was called with zero arguments, but wants at least one.
    Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1003327653}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "scalpl" "btce">

**Comment by adlai** [comment]
This has been fixed.
