### ISSUE TITLE
scalpl.bitmex does not build for me

### ISSUE THREAD

**Issue by quicklisp** [adlai/scalpl#8]
https://github.com/adlai/scalpl/blob/886f956a7b243fcab796a04f40ac2717e2212214/bitmex.lisp#L100

This triggers a package variance warning in SBCL when the defpackage form is loaded. The log is here: http://report.quicklisp.org/2019-12-24/failure-report/scalpl.html#scalpl.bitmex

**Comment by quicklisp** [comment]
I think adding swagger to the export clause would fix it.

**Comment by adlai** [comment]
Thank you for reporting this warning.
